//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurPresence.Modeller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OurPresence.Modeller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Build Command - complete.
        /// </summary>
        internal static string BuildComplete {
            get {
                return ResourceManager.GetString("BuildComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build command failed.
        /// </summary>
        internal static string BuildFailed {
            get {
                return ResourceManager.GetString("BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Build Command - OnExecute.
        /// </summary>
        internal static string BuildOnExecute {
            get {
                return ResourceManager.GetString("BuildOnExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeller Complete.
        /// </summary>
        internal static string CompleteEvent {
            get {
                return ResourceManager.GetString("CompleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Command - OnExecute.
        /// </summary>
        internal static string CreateOnExecture {
            get {
                return ResourceManager.GetString("CreateOnExecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator List Command - complete.
        /// </summary>
        internal static string ListComplete {
            get {
                return ResourceManager.GetString("ListComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List command failed.
        /// </summary>
        internal static string ListFailed {
            get {
                return ResourceManager.GetString("ListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator List Command - OnExecute.
        /// </summary>
        internal static string ListOnExecute {
            get {
                return ResourceManager.GetString("ListOnExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings: {0}, Target: {1}, Overwrite: {2}, Verbose: {3}.
        /// </summary>
        internal static string ParameterEvent {
            get {
                return ResourceManager.GetString("ParameterEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings command failed.
        /// </summary>
        internal static string SettingsFailed {
            get {
                return ResourceManager.GetString("SettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Settings Command - OnExecute.
        /// </summary>
        internal static string SettingsOnExecute {
            get {
                return ResourceManager.GetString("SettingsOnExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify a command.
        /// </summary>
        internal static string SpecifyCommand {
            get {
                return ResourceManager.GetString("SpecifyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Update Command - complete.
        /// </summary>
        internal static string UpdateComplete {
            get {
                return ResourceManager.GetString("UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update command failed.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Update Command - OnExecute.
        /// </summary>
        internal static string UpdateOnExecute {
            get {
                return ResourceManager.GetString("UpdateOnExecute", resourceCulture);
            }
        }
    }
}
